# This workflow runs tests for the ormir_xct Python environment

name: Test ormir_xct Python Env on Mac, Linux, Windows

on: [push]

jobs:
  test-windows-linux:
    name: Windows and Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version:: [3.11.11]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11.11
          miniconda-version: 'latest'
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment.yml
      - run: |
          conda info
          conda list
          python -c "import itk"
          python -c "import vtk"
          python -c "import SimpleITK"
          python -c "import ormir-xct"
          
  test-apple-silicon:
    name: Apple Silicon
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-15"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: setup-miniforge
        continue-on-error: true
        with:
          miniforge-version: latest
      - name: Check arm64
        shell: bash -el {0}
        run: |
          conda install -y python
          python -c "import platform; assert platform.machine() == 'arm64', platform.machine()"
      - name: Check dependency install
        shell: bash -el {0}
        run: |
          conda install -y python
          pip install -r requirements.txt
          pconda info
          conda list
          python -c "import itk"
          python -c "import vtk"
          python -c "import SimpleITK"
          python -c "import ormir-xct"